version: "2"
services:

  colonization:
    image: ctjinx/colonization:local
    depends_on:
      - spaceship
      - targeting

  spaceship:
    environment:
      - REDIS_HOST=spaceship-redis
      - INTEGRATION_TEST=true
    depends_on:
      - spaceship-redis

  spaceship-redis:
    image: ctjinx/alpine-redis

  targeting:
    environment:
      - LOCAL_S3=targeting-s3
    depends_on:
      - targeting-s3

  targeting-s3:
    image: ctjinx/local-s3
    volumes:
      - ./tests/s3-buckets:/app/mockData
